
BLENDER="E:\Program Files\Blender Foundation\Blender 2.90\blender.exe"
DIST=../dist

all : \
    $(DIST)/pentaton.pnct \
    $(DIST)/pentaton.scene \

$(DIST)/pentaton.scene : pentaton.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "pentaton.blend:Main" "$(DIST)/pentaton.scene"

$(DIST)/pentaton.pnct : pentaton.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "pentaton.blend:Main" "$(DIST)/pentaton.pnct" 
